name: Build and Release AppImage

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download AppImageTool
        run: |
          wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Build AppImage
        run: |
          ./appimagetool-x86_64.AppImage sscom.AppDir

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: sscom-x86_64.AppImage
          tag_name: continuous
          name: Continuous Build
          body: Automatic build from main branch
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}