name: Build and Release AppImage

on:
  release:
    types: [created]

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download AppImageTool
        run: |
          wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Build AppImage
        run: |
          ./appimagetool-x86_64.AppImage sscom.AppDir
          # 生成文件名格式：应用名-版本号-x86_64.AppImage
          RELEASE_NAME=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
          mv sscom-x86_64.AppImage sscom-$RELEASE_NAME-x86_64.AppImage

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./sscom-$RELEASE_NAME-x86_64.AppImage
          asset_name: sscom-$RELEASE_NAME-x86_64.AppImage
          asset_content_type: application/octet-stream